authorName: p3jawors
experimentName: llp_scan
# how many to run simultaneously
trialConcurrency: 1
maxExecDuration: 128h
maxTrialNum: 20000
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: neural_search_space.json
useAnnotation: false
logDir: /home/pjaworsk/src/masters/masters_thesis/masters_thesis/nni_scripts
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  # includeIntermediateResults: true
  classArgs:
    optimize_mode: minimize
# The path and the running command of trial
trial:
  command: python /home/pjaworsk/src/masters/masters_thesis/masters_thesis/eval_params.py nni 30000
  codeDir: .
# assessor:
#   builtinAssessorName: Curvefitting
#   classArgs:
#     optimize_mode: maximize
#     epoch_num: 10
#     threshold: 0.9
